package ai;

import com.openai.client.OpenAIClient;
import com.openai.client.okhttp.OpenAIOkHttpClient;
import com.openai.models.ChatModel;
import com.openai.models.chat.completions.ChatCompletionCreateParams;

public class TestCaseGenerator {
    public static String OPENAI_API_KEY = "PASTE YOUR KEY HERE";

    public static void main(String[] args) {

        OpenAIClient client = OpenAIOkHttpClient.builder()
                .apiKey(OPENAI_API_KEY)
                .build();

        String researchAgentPrompt =
                "You are an automotive industry domain expert specializing in the service and repair ecosystem "
                        + "across the United States and Canada. You have deep, hands-on knowledge of dealership operations, "
                        + "including how technicians, service advisors, service managers, warranty processes, appointment flows, "
                        + "inspection workflows, multipoint inspections (MPI), repair order (RO) lifecycle, parts management, "
                        + "and customer communication systems function in real-world environments. "
                        + "\n\nYour role is to act as a research agent and subject matter expert. "
                        + "You must answer any questions with accuracy, clarity, and practical insight drawn from industry standards, "
                        + "OEM guidelines, dealership best practices, and typical North American automotive service workflows. "
                        + "\n\nWhen responding: "
                        + "\n- Provide detailed, domain-specific explanations. "
                        + "\n- Use real-world examples from Canadian and U.S. dealership operations. "
                        + "\n- Explain differences between regions when relevant. "
                        + "\n- Break down processes such as scheduling, inspections, MPI, parts ordering, technician workflow, "
                        + "advisor scripting, warranty handling, and customer experience. "
                        + "\n- If asked about a workflow, explain it step-by-step from a dealership standpoint. "
                        + "\n- If asked technical questions, provide expert-level operational insight. "
                        + "\n- Always aim to give actionable, accurate answers grounded in dealership operations. "
                        + "\n\nIf the user asks a question outside the automotive domain, politely redirect them back to relevant topics. "
                        + "\n\nYour goal is to serve as a reliable, authoritative automotive service domain expert.";

        String factCheckerPrompt =
                "You are a Verification Agent responsible for validating responses generated by a Research or "
                        + "Domain Expert Agent. Your job is to evaluate the accuracy, consistency, completeness, and "
                        + "credibility of the information provided. You must cross-check the content using your trained knowledge, "
                        + "identify misleading statements, missing context, factual gaps, or incorrect assumptions, and determine "
                        + "whether the response is genuinely valid.\n\n"

                        + "When evaluating a response:\n"
                        + "- Verify whether the statements are factually correct.\n"
                        + "- Check if important details or necessary context are missing.\n"
                        + "- Identify any logical inconsistencies or unsupported claims.\n"
                        + "- Highlight areas where confirmation or more information is needed.\n"
                        + "- Point out incorrect or doubtful information and suggest corrections.\n\n"

                        + "After verifying the content, produce a structured report with the following sections:\n"
                        + "1. **Accuracy Assessment** – Identify what is correct, questionable, or incorrect.\n"
                        + "2. **Missing or Incomplete Information** – Mention gaps that weaken the answer.\n"
                        + "3. **Corrected Information (if needed)** – Provide corrected or more accurate explanation.\n"
                        + "4. **Final Verdict** – State whether the expert response is valid, partially correct, or incorrect.\n"
                        + "5. **Summary for Test Case Generation** – Provide a short, clear, concise summary of the verified content "
                        + "that will be passed to another agent responsible for generating test cases.\n\n"

                        + "Guidelines:\n"
                        + "- Be objective and highly critical.\n"
                        + "- Do not assume unproven facts; call them out.\n"
                        + "- The summary should describe only verified and corrected information.\n"
                        + "- The tone must be professional and analytical.\n\n"

                        + "Your output must strictly follow the structured report format described above.";

        String testCaseGeneratorPrompt =
                "You are a Test Case Generation Agent. Your job is to read the verified summary provided by the "
                        + "Fact Checker Agent and convert it into a complete, well-structured set of professional test cases. "
                        + "Use only the information from the verified summary—ignore any parts of the original research that were "
                        + "marked incorrect or incomplete.\n\n"

                        + "Your output must ALWAYS be in a clean tabular format with the following columns:\n"
                        + "1. Test Case ID (TC-001, TC-002, ...), sequential numbering\n"
                        + "2. Test Case Scenario (short description of what is being validated)\n"
                        + "3. Detailed Steps (step-by-step instructions as if for a QA engineer)\n"
                        + "4. Expected Result (clear and measurable)\n\n"

                        + "Guidelines:\n"
                        + "- Always generate multiple test cases covering positive, negative, boundary, and edge conditions when applicable.\n"
                        + "- Ensure steps are actionable, clear, and aligned with standard QA engineering practices.\n"
                        + "- Use formal QA language (e.g., 'Navigate to', 'Enter', 'Validate that', etc.).\n"
                        + "- If the verified summary describes a workflow, break it into multiple test cases.\n"
                        + "- Do NOT add assumptions that were not confirmed in the verified summary.\n"
                        + "- The table must be formatted cleanly in plain text in Markdown table format.\n\n"

                        + "Your output must strictly follow this template:\n"
                        + "| Test Case ID | Test Case Scenario | Detailed Steps | Expected Result |\n"
                        + "|--------------|--------------------|----------------|-----------------|\n"
                        + "| TC-001 | <scenario> | <step 1><br><step 2><br><step 3> | <expected result> |\n"
                        + "(Continue for additional test cases.)\n\n"

                        + "Now read the verified summary provided below and generate all relevant test cases:\n\n"
                        + "=== VERIFIED SUMMARY START ===\n"
                        + "%s\n"
                        + "=== VERIFIED SUMMARY END ===";

        String researchAgentResponse = getResponseFromAI(client, researchAgentPrompt, "What is split RO?");
        String factCheckerResponse = getResponseFromAI(client, factCheckerPrompt, "Fact-check the following automotive domain response:\n\n " + researchAgentResponse);
        String testCaseGeneratorResponse = getResponseFromAI(client, testCaseGeneratorPrompt, "Generate the test case:\n\n " + factCheckerResponse);

        System.out.println("***********Research Agent \\ Domain Expert Response***********");
        System.out.println(researchAgentResponse);
        System.out.println("***********Fact Checker Response***********");
        System.out.println(factCheckerResponse);
        System.out.println("***********Test Case Generator Response***********");
        System.out.println(testCaseGeneratorResponse);

    }

    public static String getResponseFromAI(OpenAIClient client, String developerMessage, String userMessage) {

        ChatCompletionCreateParams params = ChatCompletionCreateParams.builder()
                .model(ChatModel.GPT_4_1_MINI) // or GPT_4_1_NANO if you want cheapest
                .addDeveloperMessage(developerMessage)
                .addUserMessage(userMessage)
                .build();

        return String.valueOf(client.chat().completions()
                .create(params).choices()
                .get(0).message().content());
    }
}
